# Generated by Django 3.1.4 on 2020-12-23 19:34

from django.db import migrations


def prepopulate(apps, schema_editor):
    Profiles = apps.get_model('profiles', 'Profiles')
    Settings = apps.get_model('profiles', 'Settings')
    Following = apps.get_model('profiles', 'User_following')
    Communities = apps.get_model('profiles', 'Communities')
    Member = apps.get_model('profiles', 'Community_members')
    Community_socials = apps.get_model('profiles', 'Community_socials')
    User_socials = apps.get_model('profiles', 'User_socials')
    Recommendations = apps.get_model('profiles', 'Recommendations')

    shravanH = Profiles(
        uuid="df6f1d0b-95b4-47c7-8c2e-844392961777",
        first_name="Shravan",
        last_name="Hariharan",
        major="Computer Science",
        grad_year=2023,
        bio="It's me, Shravan!"
    )
    shravanH.save()
    Settings(user=shravanH).save()
    User_socials(
        user=shravanH,
        discord="shravanH@4571",
        facebook="https::www.facebook.com/../shravanHfb",
        snapchat="shravanH",
        instagram="shravanH",
        github="shravanH2001",
        linkedin="https://linkedin.com/user/shravan1",
        email="shravan@ucsd.edu"
    ).save()
    

    shravanK = Profiles(
        uuid="16d9c560-fc43-4037-8690-9ca14de155d6",
        first_name="Shravan",
        last_name="Konduru",
        major="Computer Science",
        grad_year=2024,
        bio="It's me, Shravan!"
    )
    shravanK.save()
    Settings(user=shravanK).save()
    User_socials(
        user=shravanK,
        discord="shravanK@2313",
        facebook="https::www.facebook.com/../shravanKfb",
        snapchat="shravanK",
        instagram="shravanK",
        github="shravanK2002",
        linkedin="https://linkedin.com/user/shravan2",
        email="shravan2@ucsd.edu"
    ).save()

    kunal = Profiles(
        uuid="7ddd1fdb-38a5-4af1-8543-8acf00305c8e",
        first_name="Kunal",
        last_name="Arora",
        major="Math-CS",
        grad_year=2023,
        bio="It's me, Kunal!"
    )
    kunal.save()
    Settings(user=kunal, following_visibility=False).save()
    User_socials(
        user=shravanH,
        discord="kunal@4211",
        facebook="https::www.facebook.com/../kunalfb",
        snapchat="kunal7271",
        instagram="not_kunal",
        github="aroralanuk",
        linkedin="https://linkedin.com/user/kunalarora2001",
        email="kuarora@ucsd.edu"
    ).save()

    bryce = Profiles(
        uuid="a855c16f-d678-4849-9ef9-1d04a0a19bd7",
        first_name="Bryce",
        last_name="Tsuyuki",
        major="Computer Science",
        grad_year=2023,
        bio="It's me, Bryce!"
    )
    bryce.save()
    Settings(user=bryce, follower_visibility=False).save()
    User_socials(
        user=shravanH,
        discord="bryceT@4171",
        facebook="https::www.facebook.com/../bryceTfb",
        snapchat="pentallelogram",
        instagram="pentallelogram",
        github="pentallelogram",
        linkedin="https://linkedin.com/user/pentallelogram",
        email="brycetsu@ucsd.edu"
    ).save()

    kim = Profiles(
        uuid="e25cbea0-8dc4-44f5-b3ce-b92062c185ae",
        first_name="Kim",
        last_name="Jong-Un",
        major="Poltical Science",
        grad_year=2021
    )
    kim.save()
    Settings(user=kim, following_visibility=False, follower_visibility=False, profile_visibility=False).save()
    User_socials(
        user=shravanH,
        discord="timJU@9999",
        facebook="https::www.facebook.com/../timfb",
        snapchat="supreme_leader",
        instagram="supreme_leader",
        github="supreme_leader",
        linkedin="https://linkedin.com/user/supreme_leader",
        email="supremeLeader@northKorea.org"
    ).save()
    
    Following(follower=shravanH, following=shravanK).save()
    Following(follower=shravanH, following=kunal).save()
    Following(follower=shravanH, following=bryce).save()
    Following(follower=shravanK, following=shravanH).save()
    Following(follower=shravanK, following=bryce).save()
    Following(follower=kunal, following=bryce).save()
    Following(follower=kunal, following=bryce).save()
    Following(follower=kunal, following=kim).save()
    Following(follower=kim, following=kunal).save()

    Recommendations(user=shravanH, recommendation=shravanK, similarity=1).save()
    Recommendations(user=shravanK, recommendation=shravanH, similarity=1).save()
    Recommendations(user=shravanK, recommendation=bryce, similarity=1).save()
    Recommendations(user=bryce, recommendation=shravanK, similarity=1).save()
    Recommendations(user=shravanH, recommendation=bryce, similarity=2).save()
    Recommendations(user=bryce, recommendation=shravanH, similarity=2).save()
    Recommendations(user=kunal, recommendation=shravanH, similarity=1).save() 
    Recommendations(user=shravanH, recommendation=kunal, similarity=1).save()
    Recommendations(user=shravanK, recommendation=kunal, similarity=0).save()
    Recommendations(user=kunal, recommendation=shravanK, similarity=0).save()
    Recommendations(user=bryce, recommendation=shravanH, similarity=2).save()
    Recommendations(user=shravanH, recommendation=bryce, similarity=2).save()
    Recommendations(user=kim, recommendation=bryce, similarity=0).save()
    Recommendations(user=bryce, recommendation=kim, similarity=0).save()
    Recommendations(user=kim, recommendation=shravanH, similarity=0).save()
    Recommendations(user=shravanH, recommendation=kim, similarity=0).save()
    Recommendations(user=kim, recommendation=shravanK, similarity=0).save()
    Recommendations(user=shravanK, recommendation=kim, similarity=0).save()
    Recommendations(user=kim, recommendation=kunal, similarity=0).save()
    Recommendations(user=kunal, recommendation=kim, similarity=0).save()

    bookclub = Communities(
        title="Book club",
        description="Welcome to the ACM Book Club where the voracious of readers share what they're currently reading and enjoying"
    )
    bookclub.save()
    Member(community=bookclub, member=bryce, admin=True).save()
    Member(community=bookclub, member=shravanK).save()
    Member(community=bookclub, member=shravanH).save()
    Community_socials(community=bookclub, discord="invite link", facebook="../bookclubACMUCSD", instagram="../bookclubamcucsd").save()

    leetcode = Communities(
        title="ACM X WIC LeetCode",
        description="Welcome to the ACM X WIC LeetCode! We solve Leetcode problems together every Sunday at 6pm."
    )
    leetcode.save()
    Member(community=leetcode, member=shravanH, admin=True).save()
    Member(community=leetcode, member=kunal, admin=True).save()
    Community_socials(community=leetcode, discord="invite link for leetcode", facebook="../leetcode", instagram="../leetcode").save()

    hackerman = Communities(
        title="Capture The Flag club",
        description="Welcome to the Capture The Flag club! We solve CTF problems together."
    )
    hackerman.save()
    Member(community=hackerman, member=kim, admin=True).save()
    Member(community=hackerman, member=shravanH).save()
    Member(community=hackerman, member=shravanK).save()
    Community_socials(community=bookclub, discord="invite link for CTF", facebook="../cyberCTF@UCSD", instagram="../cyberCTF@ACM").save()



class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(prepopulate),
    ]

