# Generated by Django 3.1.3 on 2020-11-24 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201117_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communities',
            name='active',
            field=models.BooleanField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='communities',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='communities',
            name='profile_image_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='community_socials',
            name='discord',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='community_socials',
            name='facebook',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='community_socials',
            name='instagram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='grad_year',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='major',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user_following',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='profiles.profiles'),
        ),
        migrations.AlterField(
            model_name='user_following',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='profiles.profiles'),
        ),
        migrations.AlterField(
            model_name='user_socials',
            name='discord',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user_socials',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user_socials',
            name='facebook',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user_socials',
            name='github',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user_socials',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user_socials',
            name='snapchat',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
