# Generated by Django 3.1.3 on 2020-12-02 22:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201124_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communities',
            name='ucid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
