# Generated by Django 3.1.2 on 2020-11-15 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communities',
            fields=[
                ('ucid', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('profile_image_link', models.CharField(max_length=255)),
                ('active', models.BooleanField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('uuid', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('grad_year', models.IntegerField()),
                ('profile_pic', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=255)),
                ('following', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User_socials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('snapchat', models.CharField(max_length=255)),
                ('github', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='profiles.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_visibility', models.BooleanField(default=True)),
                ('follower_visibility', models.BooleanField(default=True)),
                ('following_visibility', models.BooleanField(default=True)),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='profiles.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Community_socials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('ucid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='profiles.communities')),
            ],
        ),
        migrations.CreateModel(
            name='Community_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='profiles.profiles')),
                ('ucid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='profiles.communities')),
            ],
        ),
    ]
