language: python
python:
- '3.8'
services:
- docker
install:
- pip install pipenv
- pipenv sync
before_script:
- source ./env-setup.sh
- docker-compose up -d
script:
- pipenv run lint
- pipenv run test
env:
  global:
  - secure: JygsEl6tfACAwL84grYHR+I1pAZw8q7bXx97sTjnpeljesWkuaHSffPrGg48gQSEib659GHCSbiHLWkjmuc1Os0/Aksj4F7SjUq4a0r2DSwV6BF1PW0tcO8We2sgU5TbmLJEU8b1Qk0ZGJDAOdEghRZtzK0+Pseeqbx4z0l2Om8MAbhE8PJCP3xnoCs5l6GYlYGRkvhwUc95gnHNv/aJ7+kq9nyEGlFeggLfy81Haq28BBZUTf8T1RVtf3Uff1ZvMAL5uL4SmPuJCvvBynzG25C0GwPi9Gbi3u1KuwzBCEhKs55tYKXxtMUne2MlLXU9SWtGadEbmFEweBcDx9Y4EEQiyPbYN+LZVdnn6MAxkIPaWtb2hRgP+JrVXAXgkm2kLojbZWUgQVIHmL4j2++0aD2Duw9New9c8mI/u02qtpeRxsufd4qF9zzdM/bUAmg3WOG7H+oThFHHG5ZG7TV/zWUvHx/nRd6xkENoPG3dP4dof7wrUhQ3BSi9bzb+FQlo8ood8ZsDnnHh3XRaxiEj46ZBFoJocSMkzuiGITfFXdtMbQV1NG8krjvesn+u5Uea408KWEaNoAj9yCjNekIy5dg44Aw+4fjJ/8gP021TqvLapQ7fO+tlI8bdtuCocMayLIK1C50NO7F3B32HaOqieou4Gd7ckrPY6RSDvSp5yls=
  - DATABASE_URL=postgres://testuser:secret@localhost:5432/travis_ci_test
  - MEMBERSHIP_PORTAL_API=http://acmucsd-membership-portal-api.herokuapp.com/
  - secure: TK5peNrFB0s5TF5S7MASAdTu3bgNMP+ujO3smRH3iMUooGgJBdzTuV6CodkyRnk9f1scbS0ORWDkGH756eKOxIIMOaKj1gSpIG7hzWKYorx3gDdVn2pNc7gvuDagkNga0GxDvHoGFJU8UPk6hS910ULFg1nE3HYyy/tm3ERBBcXQKWSTqtwYFNRgH68UGlgh6XuLlPR03jpK+EeoPaJSP3Wq15uBAmJtnOPR8OVh3khA2Kmjc5QU3dquycI14Zg2K0ldY+gFfoeKfsUJgIBrGTUAMc5j+J9AHBb36Aty2cIvJlmIYIC3lMr7entAJ/PxWxYKRI/hid6qiFFupwCbCdaWi5To4Ku7z0j4XPPIEy+ZXD/LN4URBusas2nuHemptMLLi24Ogsqy8wt9EYIwfZuk7Fv0A+VAyUYSkOcjcTzZzJ4qH6XCaueeIcW4ZsYoMRp8I6xSOno4TIxNt5brvB2+ud1D4pgOZE0kwlajKNL7TCHsL10R0oip+4Rv8b8DYQVXDbcYq456gikbakSTvKi4rM8v4Lc9UbyDoaxMlAiFdx9tZ0a2Wy/bvPzAjIBx1bxMwF5eLthxjMvjQC8dskt8OzXnZr7sNg1LYA16gk+jb/guIedMPuQN234FkRCf0PfdTK76bV3Qd2nDq7OFoIJgqH5LsmqfBwvSzsGTDPY=
